services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: h5p

    ports:
      - "3308:3306"
    restart: always

volumes:
  ###> doctrine/doctrine-bundle ###
  database_h5p:
###< doctrine/doctrine-bundle ###
