
services:
  database:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "saSsd21-asd112A!1e14"
      MYSQL_DATABASE: h5p

    ports:
      - "3310:3306"
    restart: always
    volumes:
      - database_h5p:/var/lib/mysql
volumes:
  database_h5p:
