import type { Config } from "tailwindcss";
import type { PluginAPI } from "tailwindcss/types/config";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  safelist: [
    'glass-card',
    'glass-card-strong',
    'elevated-card',
    'interactive-element',
    'focus-ring',
    'nav-link',
    'btn-primary',
    'btn-secondary',
    'btn-ghost',
    'form-input',
    'form-label',
    'loading-shimmer',
    'loading-pulse',
    'loading-spinner',
    'status-success',
    'status-warning',
    'status-error',
    'status-info',
    'h5p-container-fluid',
    'animate-fade-in-down',
    'animate-fade-in-up',
    'animate-fade-in',
    'animate-spin',
    'animate-pulse',
    'animate-float',
    'animate-slide-in-right',
    'animate-slide-in-left',
    'banner-decoration',
    'banner-decoration-circle',
    'banner-circle-1',
    'banner-circle-2',
    'banner-circle-3',
    'banner-circle-4',
    'banner-circle-5',
    'bg-primary/10',
    'hover:bg-primary/10',
    'bg-primary/20',
    'bg-base-200/50',
    'hover:bg-base-200/50',
    'text-primary',
    'bg-primary',
    'rotate-90',
    'opacity-0',
    'opacity-100',
    'rotate-45',
    'translate-y-2',
    '-rotate-45',
    '-translate-y-2',
  ],
  future: {
    respectDefaultRingColorOpacity: true,
    hoverOnlyWhenSupported: true,
  },
  theme: {
    screens: {
      'xs': '380px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
      '4xl': '2560px',
      // Geräte-spezifische Breakpoints
      'mobile': {'max': '767px'},
      'tablet': {'min': '768px', 'max': '1023px'},
      'desktop': {'min': '1024px'},
      'widescreen': {'min': '1920px'},
      'ultrawide': {'min': '2560px'},
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--color-primary))',
          dark: 'rgb(var(--color-primary-dark))',
          50: 'rgb(239 246 255)',
          100: 'rgb(219 234 254)',
          200: 'rgb(191 219 254)',
          300: 'rgb(147 197 253)',
          400: 'rgb(96 165 250)',
          500: 'rgb(var(--color-primary))',
          600: 'rgb(var(--color-primary-dark))',
          700: 'rgb(29 78 216)',
          800: 'rgb(30 64 175)',
          900: 'rgb(30 58 138)',
          950: 'rgb(23 37 84)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--color-secondary))',
          50: 'rgb(245 243 255)',
          100: 'rgb(237 233 254)',
          200: 'rgb(221 214 254)',
          300: 'rgb(196 181 253)',
          400: 'rgb(167 139 250)',
          500: 'rgb(var(--color-secondary))',
          600: 'rgb(124 58 237)',
          700: 'rgb(109 40 217)',
          800: 'rgb(91 33 182)',
          900: 'rgb(76 29 149)',
          950: 'rgb(46 16 101)',
        },
        accent: 'rgb(var(--color-accent))',
        success: 'rgb(var(--color-success))',
        warning: 'rgb(var(--color-warning))',
        error: 'rgb(var(--color-error))',
        info: 'rgb(var(--color-info))',
        background: {
          primary: 'rgb(var(--bg-primary))',
          secondary: 'rgb(var(--bg-secondary))',
          tertiary: 'rgb(var(--bg-tertiary))',
          elevated: 'rgb(var(--bg-elevated))',
        },
        foreground: {
          primary: 'rgb(var(--text-primary))',
          secondary: 'rgb(var(--text-secondary))',
          tertiary: 'rgb(var(--text-tertiary))',
          inverse: 'rgb(var(--text-inverse))',
          muted: 'rgb(var(--text-muted))',
        },
        border: {
          primary: 'rgb(var(--border-primary))',
          secondary: 'rgb(var(--border-secondary))',
          focus: 'rgb(var(--border-focus))',
          hover: 'rgb(var(--border-hover))',
        },
      },
      fontFamily: {
        primary: ['var(--font-primary)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: ['var(--font-size-xs)', { lineHeight: '1.4' }],
        sm: ['var(--font-size-sm)', { lineHeight: '1.4' }],
        base: ['var(--font-size-base)', { lineHeight: '1.6' }],
        lg: ['var(--font-size-lg)', { lineHeight: '1.6' }],
        xl: ['var(--font-size-xl)', { lineHeight: '1.6' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: '1.4' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: '1.2' }],
        '4xl': ['var(--font-size-4xl)', { lineHeight: '1.1' }],
      },
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none: 'none',
      },
      animation: {
        'fade-in-down': 'fadeInDown 0.5s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.5s ease-out forwards',
        'fade-in': 'fadeIn 0.3s ease-out forwards',
        'spin': 'spin 1s linear infinite',
        'spin-slow': 'spin 3s linear infinite',
        'spin-slower': 'spin 5s linear infinite',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s infinite',
        'slide-in-right': 'slideInRight 0.3s ease-out forwards',
        'slide-in-left': 'slideInLeft 0.3s ease-out forwards',
      },
      keyframes: {
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        spin: {
          to: {
            transform: 'rotate(360deg)',
          },
        },
        pulse: {
          '50%': {
            opacity: '.5',
          },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        normal: 'var(--transition-normal)',
        slow: 'var(--transition-slow)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-primary': 'linear-gradient(135deg, rgb(var(--color-primary)), rgb(var(--color-secondary)))',
        'gradient-glass': 'linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0.05))',
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        fixed: 'var(--z-fixed)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
        toast: 'var(--z-toast)',
      },
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '40px',
      },
    },
  },
  plugins: [
    require("daisyui"),
    function({ addUtilities, addComponents, theme }: PluginAPI) {
      const newUtilities = {
        '.pattern-dots': {
          backgroundImage: `radial-gradient(rgb(var(--text-tertiary)) 1px, transparent 1px)`,
          backgroundSize: '20px 20px',
        },
        '.pattern-grid': {
          backgroundImage: `
            linear-gradient(rgb(var(--border-primary)) 1px, transparent 1px),
            linear-gradient(90deg, rgb(var(--border-primary)) 1px, transparent 1px)
          `,
          backgroundSize: '20px 20px',
        },
        '.text-gradient': {
          background: 'linear-gradient(135deg, rgb(var(--color-primary)), rgb(var(--color-secondary)))',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
          backgroundClip: 'text',
        },
        '.container-fluid-center': {
          maxWidth: '1200px',
          marginLeft: 'auto',
          marginRight: 'auto',
          paddingLeft: theme('spacing.4') as string,
          paddingRight: theme('spacing.4') as string,
          '@screen sm': {
            paddingLeft: theme('spacing.6') as string,
            paddingRight: theme('spacing.6') as string,
          },
          '@screen md': {
            paddingLeft: theme('spacing.8') as string,
            paddingRight: theme('spacing.8') as string,
          },
          '@screen lg': {
            paddingLeft: theme('spacing.md') as string,
            paddingRight: theme('spacing.md') as string,
          },
          '@screen xl': {
            maxWidth: '1400px',
          },
          '@screen 2xl': {
            maxWidth: '1600px',
          },
          '@screen 3xl': {
            maxWidth: '1920px',
          },
          '@screen 4xl': {
            maxWidth: '2400px',
            paddingLeft: theme('spacing.xl') as string,
            paddingRight: theme('spacing.xl') as string,
          },
        },
        '.text-responsive': {
          fontSize: 'clamp(0.875rem, 2.5vw, 1.125rem)',
          lineHeight: '1.6',
        },
        '.text-responsive-lg': {
          fontSize: 'clamp(1.125rem, 4vw, 2rem)',
          lineHeight: '1.4',
        },
        '.text-responsive-xl': {
          fontSize: 'clamp(1.5rem, 5vw, 3.5rem)',
          lineHeight: '1.2',
        },
        '.text-responsive-2xl': {
          fontSize: 'clamp(2rem, 6vw, 4.5rem)',
          lineHeight: '1.1',
        },
        '.spacing-responsive': {
          padding: 'clamp(1rem, 4vw, 2rem)',
        },
        '.spacing-responsive-sm': {
          padding: 'clamp(0.5rem, 2vw, 1rem)',
        },
        '.spacing-responsive-lg': {
          padding: 'clamp(2rem, 6vw, 4rem)',
        },
        '.grid-responsive': {
          display: 'grid',
          gap: theme('spacing.4') as string,
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          '@screen sm': {
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
            gap: theme('spacing.6') as string,
          },
          '@screen md': {
            gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))',
            gap: theme('spacing.8') as string,
          },
          '@screen lg': {
            gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))',
          },
          '@screen xl': {
            gridTemplateColumns: 'repeat(auto-fit, minmax(450px, 1fr))',
          },
        },
        '.aspect-responsive': {
          aspectRatio: '16/9',
          '@screen mobile': {
            aspectRatio: '4/3',
          },
        },
      };

      const newComponents = {
        '.card-modern': {
          backgroundColor: 'rgb(var(--bg-elevated))',
          border: '1px solid rgb(var(--border-primary))',
          borderRadius: theme('borderRadius.xl') as string,
          boxShadow: theme('boxShadow.md') as string,
          transition: 'all var(--transition-normal)',
          '&:hover': {
            boxShadow: theme('boxShadow.xl') as string,
            transform: 'translateY(-2px)',
          },
        },
        '.input-modern': {
          width: '100%',
          padding: `${theme('spacing.sm') as string} ${theme('spacing.md') as string}`,
          border: '1px solid rgb(var(--border-primary))',
          borderRadius: theme('borderRadius.lg') as string,
          backgroundColor: 'rgb(var(--bg-secondary))',
          color: 'rgb(var(--text-primary))',
          fontSize: (theme('fontSize.sm') as [string, { lineHeight: string }])[0],
          transition: 'all var(--transition-fast)',
          '&:focus': {
            outline: 'none',
            borderColor: 'rgb(var(--color-primary))',
            boxShadow: `0 0 0 3px rgba(var(--color-primary), 0.1)`,
            backgroundColor: 'rgb(var(--bg-primary))',
          },
        },
      };
      addUtilities(newUtilities);
      addComponents(newComponents);
    },
  ],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "rgb(var(--color-primary))",
          "primary-focus": "rgb(var(--color-primary-dark))",
          "primary-content": "rgb(var(--text-inverse))",
          "secondary": "rgb(var(--color-secondary))",
          "secondary-focus": "rgb(var(--color-secondary))",
          "secondary-content": "rgb(var(--text-inverse))",
          "accent": "rgb(var(--color-accent))",
          "accent-focus": "rgb(var(--color-accent))",
          "accent-content": "rgb(var(--text-inverse))",
          "neutral": "rgb(var(--text-primary))",
          "neutral-focus": "rgb(var(--text-secondary))",
          "neutral-content": "rgb(var(--bg-primary))",
          "base-100": "rgb(var(--bg-primary))",
          "base-200": "rgb(var(--bg-secondary))",
          "base-300": "rgb(var(--bg-tertiary))",
          "base-content": "rgb(var(--text-primary))",
          "info": "rgb(var(--color-info))",
          "success": "rgb(var(--color-success))",
          "warning": "rgb(var(--color-warning))",
          "error": "rgb(var(--color-error))",

          "--rounded-box": "var(--radius-xl)",
          "--rounded-btn": "var(--radius-lg)",
          "--rounded-badge": "var(--radius-full)",
          "--animation-btn": "var(--transition-fast)",
          "--animation-input": "var(--transition-fast)",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "var(--radius-md)",
        },
      },
      {
        dark: {
          "primary": "rgb(var(--color-primary))",
          "primary-focus": "rgb(var(--color-primary-dark))",
          "primary-content": "rgb(var(--text-inverse))",
          "secondary": "rgb(var(--color-secondary))",
          "secondary-focus": "rgb(var(--color-secondary))",
          "secondary-content": "rgb(var(--text-inverse))",
          "accent": "rgb(var(--color-accent))",
          "accent-focus": "rgb(var(--color-accent))",
          "accent-content": "rgb(var(--text-inverse))",
          "neutral": "rgb(var(--text-primary))",
          "neutral-focus": "rgb(var(--text-secondary))",
          "neutral-content": "rgb(var(--bg-primary))",
          "base-100": "rgb(var(--bg-primary))",
          "base-200": "rgb(var(--bg-secondary))",
          "base-300": "rgb(var(--bg-tertiary))",
          "base-content": "rgb(var(--text-primary))",
          "info": "rgb(var(--color-info))",
          "success": "rgb(var(--color-success))",
          "warning": "rgb(var(--color-warning))",
          "error": "rgb(var(--color-error))",

          "--rounded-box": "var(--radius-xl)",
          "--rounded-btn": "var(--radius-lg)",
          "--rounded-badge": "var(--radius-full)",
          "--animation-btn": "var(--transition-fast)",
          "--animation-input": "var(--transition-fast)",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "var(--radius-md)",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    logs: true,
    prefix: "",
  },
} satisfies Config;
